Repository cloudfoundry-incubator/kubecf, pull requests merged in 2019-12, with the labels that each got.

#223 mgmt: Add github stale configuration
  .github/stale.yml
Labels: Priority: Low, Type: Maintenance

#219 Bump to cf-deployment 12.4.0
  bosh/releases/pre_render_scripts/uaa/uaa/jobs/patch_pre-start.sh
  bosh/releases/pre_render_scripts/uaa/uaa/jobs/patch_uaa.sh
  def.bzl
  deploy/helm/kubecf/assets/operations/instance_groups/adapter.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/doppler.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/router.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/scheduler.yaml
  deploy/helm/kubecf/assets/operations/set_release_versions.yaml
  deploy/helm/kubecf/assets/operations/temporary/remove_variables.yaml
  deploy/helm/kubecf/values.yaml
  testing/smoke_tests/BUILD.bazel
Labels: Priority: High, Type: Maintenance

#237 Enabled DB encryption validation
  deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
Labels: Type: Bug

#259 Bump cf-deployment to v12.18.0
  bosh/releases/pre_render_scripts/router/gorouter/jobs/patch_pre-start.sh
  def.bzl
  deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
  deploy/helm/kubecf/values.yaml
  dev/cf_deployment/bump/set_release_urls.sh
  dev/cf_deployment/bump/update_buildpack_versions.sh
Labels: Type: Maintenance

#244 Aduffeck/feature flags for tests
  .gitlab/pipelines/stages/deploy/deploy_kubecf.sh
  deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/brain-tests.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/smoke-tests.yaml
  deploy/helm/kubecf/templates/brain-tests.yaml
  deploy/helm/kubecf/values.yaml
Labels: Type: Bug

#260 Adding sle15 stack
  bosh/releases/pre_render_scripts/diego-cell/sle15-rootfs-setup/jobs/patch_pre-start.sh
  deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/sle15-stack.yaml
  deploy/helm/kubecf/values.yaml
Labels: Type: Enhancement

#243 Add Drone CI
  .drone/config.star
  .drone/deploy/runner/BUILD.bazel
  .drone/deploy/runner/def.bzl
  .drone/deploy/runner/start.sh
  .drone/deploy/server/BUILD.bazel
  .drone/deploy/server/def.bzl
  .drone/deploy/server/deploy.sh
  .drone/deploy/server/image/Dockerfile.web
  .drone/deploy/server/image/run.sh
  .drone/pipelines/default/runtime/binaries.sh
  .drone/pipelines/default/runtime/config.sh
  .drone/pipelines/default/steps/build/build.sh
  .drone/pipelines/default/steps/build/output_chart.sh
  .drone/pipelines/default/steps/deploy/cf_operator.sh
  .drone/pipelines/default/steps/deploy/cleanup.sh
  .drone/pipelines/default/steps/deploy/kind.sh
  .drone/pipelines/default/steps/deploy/kubecf.sh
  .drone/pipelines/default/steps/deploy/wait_cf_operator.sh
  .drone/pipelines/default/steps/deploy/wait_kubecf.sh
  .drone/pipelines/default/steps/test/cf_acceptance_tests.sh
  .drone/pipelines/default/steps/test/smoke_tests.sh
  .gitignore
  .gitlab/pipelines/runtime/binaries.sh
  .gitlab/pipelines/stages/deploy/deploy_kubecf.sh
  WORKSPACE
  def.bzl
  deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
  dev/external_database/def.bzl
  dev/kind/def.bzl
  dev/linters/BUILD.bazel
  dev/linters/shellcheck.sh
  doc/kube/kind.md
  rules/external_binary/BUILD.bazel
  rules/external_binary/def.bzl
  rules/helm/def.bzl
  rules/jq/BUILD.bazel
  rules/k3s/BUILD.bazel
  rules/kubectl/BUILD.bazel
  rules/kubectl/def.bzl
  rules/yaml2json/BUILD.bazel
  rules/yaml_extractor/defs.bzl
Labels: Type: CI

#273 Fix the bbs readiness probe
  deploy/helm/kubecf/assets/operations/instance_groups/diego-api.yaml
Labels: Type: Bug

#281 Enable credhub instance group
  .gitlab-ci.yml
  .gitlab/pipelines/runtime/config.sh
  .gitlab/pipelines/stages/deploy/deploy_kubecf.sh
  .gitlab/pipelines/stages/deploy/wait_kubecf.sh
  deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/brain-tests.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/credhub.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/router.yaml
  deploy/helm/kubecf/assets/operations/temporary/remove_roles.yaml
  deploy/helm/kubecf/assets/operations/temporary/remove_variables.yaml
  deploy/helm/kubecf/templates/azs.yaml
  deploy/helm/kubecf/templates/sizing.yaml
  deploy/helm/kubecf/values.yaml
Labels: Type: Enhancement

#289 Fix Drone CI
  .drone/pipelines/default/steps/deploy/kubecf.sh
Labels: Type: Bug, Type: CI
