Repository cloudfoundry-incubator/kubecf, pull requests merged in 2019-11, with the labels that each got.

#87 Consolidate and cross-link kubecf documentation.
  INSTALL.md
  bosh/releases/pre_render_scripts/README.md
  dev/README.md
  dev/cf_cli/README.md
  dev/cf_deployment/bump/README.md
  dev/kind/README.md
  dev/kubecf/README.md
  dev/kubecf/docs/accessing.md
  dev/kubecf/docs/bosh-author.md
  dev/kubecf/docs/installing.md
  doc/Contribute.md
  doc/bosh-release-development.md
  doc/cf_cli.md
  doc/cf_deployment/bump.md
  doc/dev/general.md
  doc/dev/minikube.md
  doc/helm.md
  doc/inspection.md
  doc/kube/kind.md
  doc/kube/minikube.md
  doc/linters.md
  doc/provider/gke.md
  doc/tests.md
  doc/tests_cat.md
  testing/README.md
Labels: documentation 📃

#96 CI tests with k3s
  .gitlab-ci.yml
  .gitlab/deploy/runner/kubernetes/deploy.sh
  .gitlab/deploy/runner/kubernetes/ephemeral_volume_k3s.yaml
  .gitlab/deploy/runner/kubernetes/values.yaml
  .gitlab/pipelines/config/config.sh
  .gitlab/pipelines/stages/cleanup.sh
  .gitlab/pipelines/stages/deploy/setup_k8s.sh
  .gitlab/pipelines/stages/deploy/wait.sh
  .gitlab/pipelines/stages/deploy/wait_cf_operator.sh
  .gitlab/pipelines/stages/deploy/wait_kubecf.sh
  WORKSPACE
  def.bzl
  dev/kube/local_path_provisioner/BUILD.bazel
  dev/minikube/start.sh
  rules/kubectl/apply.sh
  rules/kubectl/def.bzl
  rules/kubectl/delete.sh
  rules/kubectl/patch.sh
Labels: CI 🏭

#105 GitHub Templates and Contributing Document
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
  code-of-conduct.md
Labels: documentation 📃

#80 Add OS switch in UAA pre-start patch
  bosh/releases/pre_render_scripts/uaa/uaa/jobs/patch_pre-start.sh
Labels: enhancement ✨

#109 Add OS switch in UAA pre-start patch
  bosh/releases/pre_render_scripts/uaa/uaa/jobs/patch_pre-start.sh
Labels: do not merge 🚫, duplicate

#111 Add test/pr/* to trigger common jobs
  .gitlab-ci.yml
Labels: CI 🏭

#115 Fix smoke-tests exit code
  .gitlab/pipelines/stages/tests/smoke_tests.sh
  def.bzl
  dev/cf_operator/BUILD.bazel
  doc/dev/general.md
Labels: CI 🏭, bug 🐛

#136 docs: add release process and release template
  doc/release/release-template.md
  doc/release/release.md
Labels: documentation 📃

#137 Eirini has now a dependency to nats and should be started after the s…
  deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
Labels: bug 🐛

#140 Fixed property to disable Eirini cert-copier
  deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
Labels: bug 🐛

#134 Use Architecture Decision Records to make and persist decisions
  .adr-dir
  doc/architecture/decisions/0001-record-architecture-decisions.md
Labels: documentation 📃

#166 Fixed storage class when none is provided
  deploy/helm/kubecf/assets/operations/instance_groups/database.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/singleton-blobstore.yaml
Labels: bug 🐛

#158 Refactored implicit var generation
  deploy/helm/kubecf/templates/implicit_vars.yaml
Labels: enhancement ✨

#176 Fixed Eirini app logs
  deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
Labels: bug 🐛

#178 Bumped CI docker image
  .gitlab-ci.yml
Labels: CI 🏭

#161 Add yaml linting
  .gitlab-ci.yml
  WORKSPACE
  def.bzl
  dev/linters/BUILD.bazel
  dev/linters/requirements.txt
  dev/linters/run_yamllint.py
  dev/linters/yamllint.sh
  doc/Contribute.md
  doc/linters.md
Labels: CI

#188 Fix ssh-proxy
  .gitlab/pipelines/runtime/config.sh
  .gitlab/pipelines/stages/deploy/deploy_kubecf.sh
  deploy/helm/kubecf/assets/operations/instance_groups/router.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/scheduler.yaml
  deploy/helm/kubecf/templates/ingress.yaml
  deploy/helm/kubecf/values.yaml
  doc/dev/general.md
  doc/dev/minikube.md
Labels: CI, documentation

#204 Fixed routing-api IP that is used to register itself
  bosh/releases/pre_render_scripts/api/routing-api/bpm/patch_bpm.sh
  deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
Labels: bug

#209 Add CATS to run on CI
  .gitlab-ci.yml
  .gitlab/pipelines/stages/tests/cf_acceptance_tests.sh
Labels: CI

#160 Switch helm to use external_binary rule
  .gitlab/pipelines/stages/build/build.sh
  .gitlab/pipelines/stages/build/output_chart.sh
  .gitlab/pipelines/stages/deploy/deploy_kubecf.sh
  .gitlab/pipelines/stages/deploy/setup_k8s.sh
  .gitlab/pipelines/stages/deploy/wait_cf_operator.sh
  .gitlab/pipelines/stages/deploy/wait_kubecf.sh
  WORKSPACE
  def.bzl
  rules/external_binary/def.bzl
  rules/helm/binary.bzl
  rules/helm/def.bzl
Labels: enhancement

#208 Add tcp-router instance group
  .gitlab/pipelines/runtime/binaries.sh
  .gitlab/pipelines/runtime/config.sh
  .gitlab/pipelines/stages/deploy/deploy_kubecf.sh
  .gitlab/pipelines/stages/deploy/wait_cf_operator.sh
  .gitlab/pipelines/stages/deploy/wait_kubecf.sh
  WORKSPACE
  def.bzl
  deploy/helm/kubecf/assets/operations/instance_groups/tcp-router.yaml
  deploy/helm/kubecf/assets/operations/temporary/remove_roles.yaml
  deploy/helm/kubecf/templates/azs.yaml
  deploy/helm/kubecf/templates/ingress.yaml
  deploy/helm/kubecf/templates/sizing.yaml
  deploy/helm/kubecf/values.yaml
  doc/dev/general.md
  doc/dev/minikube.md
  rules/jq/BUILD.bazel
  rules/yaml2json/BUILD.bazel
Labels: enhancement
