Repository cloudfoundry-incubator/kubecf, pull requests merged in 2020-04, with the labels that each got.

#605 doc: Archive the done issues after each release.
  doc/release/release.md
Labels: Status: Verification Needed, Type: Documentation

#621 fix: add missing quotes when using [] syntax
  deploy/helm/kubecf/assets/operations/instance_groups/adapter.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/doppler.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/log-api.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/router.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/scheduler.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/uaa.yaml
Labels: Type: Maintenance

#622 feat: improve testing targets
  doc/tests.md
  doc/tests_brain.md
  doc/tests_cat.md
  doc/tests_sits.md
  doc/tests_smoke.md
  rules/kubecf/BUILD.bazel
  rules/kubecf/def.bzl
  rules/kubecf/test.tmpl.sh
  testing/BUILD.bazel
  testing/acceptance_tests/BUILD.bazel
  testing/acceptance_tests/trigger.yaml
  testing/brain_tests/BUILD.bazel
  testing/brain_tests/trigger.yaml
  testing/smoke_tests/BUILD.bazel
  testing/smoke_tests/trigger.yaml
  testing/sync_integration_tests/BUILD.bazel
  testing/sync_integration_tests/trigger.yaml
Labels: Priority: High, Type: Enhancement

#619 log-cache instance group
  deploy/helm/kubecf/.helmignore
  deploy/helm/kubecf/BUILD.bazel
  deploy/helm/kubecf/assets/operations/instance_groups/doppler.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/log-cache.yaml
  deploy/helm/kubecf/assets/operations/job_moving/move_auctioneer.yaml
  deploy/helm/kubecf/assets/operations/job_moving/move_log_cache.yaml
  deploy/helm/kubecf/assets/operations/job_moving/move_routing_api.yaml
  deploy/helm/kubecf/assets/operations/sizing.yaml
  deploy/helm/kubecf/templates/bosh_deployment.yaml
  deploy/helm/kubecf/templates/ops.yaml
  deploy/helm/kubecf/values.yaml
Labels: Type: Bug

#638 feat: bump cf deployment 12.36
  def.bzl
  deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/doppler.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/log-api.yaml
  deploy/helm/kubecf/values.yaml
  doc/cf_deployment/bump.md
Labels: Type: Maintenance

#639 fix: use $bytes instead of .Files.Get $path
  deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/app-autoscaler.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/auctioneer.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/bits.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/diego-api.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/router.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/routing-api.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/scheduler.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/singleton-blobstore.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/smoke-tests.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/uaa.yaml
  deploy/helm/kubecf/assets/operations/job_moving/move_log_cache.yaml
Labels: Type: Maintenance

#608 feat: Adding support for external blobstore.
  def.bzl
  deploy/helm/kubecf/assets/operations/azs.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/singleton-blobstore.yaml
  deploy/helm/kubecf/templates/bosh_deployment.yaml
  deploy/helm/kubecf/templates/ops.yaml
  deploy/helm/kubecf/templates/s3-blobstore.yaml
  deploy/helm/kubecf/values.yaml
Labels: Priority: High, SUSE

#658 fix: remove --- from routing-api ops-file
  deploy/helm/kubecf/assets/operations/instance_groups/routing-api.yaml
Labels: Type: Bug

#657 doc: adding document for external blobstore config
  doc/external_bobstore.md
Labels: SUSE, Status: Verification Needed, Type: Documentation

#695 feat: docker suite enabled by default on CATS
  deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
  deploy/helm/kubecf/values.yaml
Labels: Type: Enhancement

#723 feat: enable tasks CATS suite by detault
  deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
Labels: Type: Enhancement

#724 feat: bump SUSE buildpacks
  deploy/helm/kubecf/values.yaml
Labels: Type: Maintenance

#693 feat: user-provided ClusterRole rules for Eirini
  deploy/helm/kubecf/templates/eirini.yaml
  deploy/helm/kubecf/values.yaml
Labels: Type: Enhancement

#725 docs: Add release process for major and minor versions
  doc/release/release-guidelines.md
Labels: Priority: Medium, Status: Verification Needed, Type: Documentation

#732 feat: allow user to provide inline operations
  deploy/helm/kubecf/templates/bosh_deployment.yaml
  deploy/helm/kubecf/templates/ops.yaml
  deploy/helm/kubecf/values.yaml
Labels: Type: Enhancement

#707 feat: helm dependencies rules
  deploy/helm/kubecf/.gitignore
  rules/helm/BUILD.bazel
  rules/helm/def.bzl
  rules/helm/dependencies_charts.BUILD.bazel
  rules/helm/package.tmpl.rb
Labels: Type: Enhancement

#651 Consume eirini release
  def.bzl
  deploy/helm/kubecf/assets/operations/azs.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/bits.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/eirini-helm.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
  deploy/helm/kubecf/assets/operations/releases.yaml
  deploy/helm/kubecf/assets/operations/sizing.yaml
  deploy/helm/kubecf/requirements.lock
  deploy/helm/kubecf/requirements.yaml
  deploy/helm/kubecf/templates/bosh_deployment.yaml
  deploy/helm/kubecf/templates/eirini.yaml
  deploy/helm/kubecf/templates/ops.yaml
  deploy/helm/kubecf/values.yaml
  rules/helm/def.bzl
  rules/helm/package.tmpl.rb
Labels: Priority: High, Type: Enhancement, changelog

#765 feat: combine stemcell bumps to SUSE buildpacks
  deploy/helm/kubecf/values.yaml
Labels: Type: Maintenance

#762 feat: adding suse buildpacks ci pipeline
  .concourse/suse-buildpacks-ci/README.md
  .concourse/suse-buildpacks-ci/config.yaml
  .concourse/suse-buildpacks-ci/deploy-pipeline
  .concourse/suse-buildpacks-ci/pipeline.yaml.gomplate
  .concourse/suse-buildpacks-ci/releases.yaml
  .concourse/suse-buildpacks-ci/tasks/build.sh
  .concourse/suse-buildpacks-ci/tasks/build.yml
  .concourse/suse-buildpacks-ci/tasks/build_release.sh
  .concourse/suse-buildpacks-ci/tasks/create_pr.sh
  .concourse/suse-buildpacks-ci/tasks/create_pr.yml
Labels: Type: CI

#712 feat: use dependencies.yaml instead of def.bzl
  BUILD.bazel
  WORKSPACE
  def.bzl
  dependencies.yaml
  deploy/helm/kubecf/BUILD.bazel
  dev/kind/BUILD.bazel
  dev/kind/def.bzl
  dev/minikube/def.bzl
  rules/workspace/BUILD.bazel
  rules/workspace/WORKSPACE
  rules/workspace/def.bzl
  rules/workspace/dependencies.bzl
  rules/workspace/json_bzl_converter.py
  rules/workspace/status_converter.tmpl.sh
  rules/workspace/status_merger.tmpl.sh
  rules/workspace_status/WORKSPACE
  rules/workspace_status/def.bzl
Labels: Type: Enhancement

#737 fix: remove old mariadb bpm script
  deploy/helm/kubecf/assets/scripts/jobs/mariadb/bpm_process.sh
Labels: Type: Maintenance

#735 fix: remove SITS when Eirini is enabled
  .concourse/pipeline.yaml.gomplate
  deploy/helm/kubecf/assets/operations/instance_groups/sync-integration-tests.yaml
  deploy/helm/kubecf/assets/operations/releases.yaml
  deploy/helm/kubecf/templates/sync-integration-tests.yaml
Labels: Type: Bug, Type: CI

#582 Bump brain test release to v0.0.10.
  deploy/helm/kubecf/values.yaml
Labels: Type: Bug

#779 feat: Breaking down suse buildpacks ci pipeline.
  .concourse/suse-buildpacks-ci/buildpack-version-bump/config.yaml
  .concourse/suse-buildpacks-ci/buildpack-version-bump/pipeline.yaml.gomplate
  .concourse/suse-buildpacks-ci/buildpack-version-bump/tasks/build.sh
  .concourse/suse-buildpacks-ci/buildpack-version-bump/tasks/build.yaml
  .concourse/suse-buildpacks-ci/buildpack-version-bump/tasks/build_release.sh
  .concourse/suse-buildpacks-ci/buildpack-version-bump/tasks/create_pr.sh
  .concourse/suse-buildpacks-ci/buildpack-version-bump/tasks/create_pr.yaml
  .concourse/suse-buildpacks-ci/deploy-pipeline
  .concourse/suse-buildpacks-ci/stemcell-version-bump/config.yaml
  .concourse/suse-buildpacks-ci/stemcell-version-bump/pipeline.yaml.gomplate
  .concourse/suse-buildpacks-ci/stemcell-version-bump/tasks/build.sh
  .concourse/suse-buildpacks-ci/stemcell-version-bump/tasks/build.yaml
  .concourse/suse-buildpacks-ci/stemcell-version-bump/tasks/build_release.sh
  .concourse/suse-buildpacks-ci/stemcell-version-bump/tasks/create_pr.sh
  .concourse/suse-buildpacks-ci/stemcell-version-bump/tasks/create_pr.yaml
  .concourse/suse-buildpacks-ci/stemcell-version-bump/tasks/prep.sh
  .concourse/suse-buildpacks-ci/stemcell-version-bump/tasks/prep.yaml
Labels: Type: CI

#797 feat: bump brain-tests release to v0.0.11
  deploy/helm/kubecf/values.yaml
Labels: Type: Maintenance
