Repository cloudfoundry-incubator/kubecf, pull requests merged in 2020-03, with the labels that each got.

#425 Trigger concourse pipeline on kubecf branches
  .concourse/pipeline.yaml
Labels: Type: CI

#386 Add probes for ha igs
  deploy/helm/kubecf/assets/operations/instance_groups/auctioneer.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/diego-api.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/routing-api.yaml
Labels: Priority: High, SUSE, Status: WIP, Type: Enhancement

#393 Replace deprecated cf-mysql release with PXC (not the BOSH release)
  bosh/releases/pre_render_scripts/database/mysql/jobs/patch_galera-healthcheck_ctl.sh
  bosh/releases/pre_render_scripts/database/mysql/jobs/patch_mariadb_ctl.sh
  bosh/releases/pre_render_scripts/database/mysql/jobs/patch_pre-start-setup.sh
  deploy/helm/kubecf/assets/operations/instance_groups/database.yaml
  deploy/helm/kubecf/assets/operations/releases.yaml
  deploy/helm/kubecf/assets/scripts/jobs/pxc/active_passive_probe.sh
  deploy/helm/kubecf/assets/scripts/jobs/pxc/entrypoint.sh
  deploy/helm/kubecf/assets/scripts/jobs/pxc/functions.sh
  deploy/helm/kubecf/assets/scripts/jobs/pxc/seeder.sh
  deploy/helm/kubecf/templates/azs.yaml
  deploy/helm/kubecf/templates/database.yaml
  deploy/helm/kubecf/templates/sizing.yaml
  deploy/helm/kubecf/values.yaml
Labels: Priority: High, Status: Verification Needed, Type: Enhancement

#434 fix: allow only credhub and uaa for apps
  deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/credhub.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/uaa.yaml
  deploy/helm/kubecf/assets/scripts/jobs/cf-cli-6-linux/setup_internal_security_group.sh
  deploy/helm/kubecf/values.yaml
Labels: Type: Bug

#454 Fix secret names used in the db seeder when ns != deployment name
  deploy/helm/kubecf/templates/database.yaml
Labels: Priority: High, Status: Verification Needed, Type: Bug

#432 Bump CATs release to get proper exit codes
  deploy/helm/kubecf/values.yaml
Labels: Priority: Critical, Status: Verification Needed, Type: CI

#459 fix: use client credentials over admin password
  deploy/helm/kubecf/assets/operations/instance_groups/credhub.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/uaa.yaml
  deploy/helm/kubecf/assets/scripts/jobs/cf-cli-6-linux/setup_internal_security_group.sh
Labels: Priority: High, Type: Maintenance

#460 feat: increase CATS scale timeout
  deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
Labels: Type: Maintenance

#436 Adding SITs to kubecf concourse CI pipeline
  .concourse/pipeline.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/sync-integration-tests.yaml
Labels: Priority: Critical, Type: CI

#424 feat: allow custom certs to be used with router
  deploy/helm/kubecf/assets/operations/instance_groups/credhub.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/router.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/uaa.yaml
  deploy/helm/kubecf/assets/scripts/jobs/cf-cli-6-linux/setup_internal_security_group.sh
  deploy/helm/kubecf/templates/ingress.yaml
  deploy/helm/kubecf/templates/router_tls.yaml
  deploy/helm/kubecf/values.yaml
  doc/router_certificates.md
Labels: Type: Enhancement

#470 fix: release versioning
  rules/helm/def.bzl
  rules/helm/package.tmpl.rb
Labels: Priority: Critical, Type: Bug

#467 fix: fixing permissions issues for autoscaler db
  deploy/helm/kubecf/assets/scripts/jobs/postgres/bpm_process.sh
Labels: Priority: High, Type: Bug

#494 fix: cf-operator bundled with KubeCF
  deploy/bundle/BUILD.bazel
Labels: Priority: Critical, Type: Bug

#485 fix: security group setups
  deploy/helm/kubecf/assets/operations/instance_groups/credhub.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/uaa.yaml
  deploy/helm/kubecf/assets/scripts/jobs/cf-cli-6-linux/setup_internal_security_group.sh
  deploy/helm/kubecf/templates/router_tls.yaml
  deploy/helm/kubecf/values.yaml
Labels: Priority: Critical, Status: Verification Needed, Type: Bug

#242 Make brain tests pass.
  deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml
  deploy/helm/kubecf/templates/brain-tests.yaml
  deploy/helm/kubecf/values.yaml
Labels: Priority: Critical, SUSE, Status: Verification Needed, Type: CI

#543 doc: add some sections related with Github issues.
  CONTRIBUTING.md
Labels: Priority: High, Type: Documentation

#571 feat: image list used by KubeCF
  def.bzl
  deploy/helm/kubecf/BUILD.bazel
  deploy/helm/kubecf/assets/operations/instance_groups/credhub.yaml
  deploy/helm/kubecf/assets/operations/releases.yaml
  deploy/helm/kubecf/defs.bzl
  deploy/helm/kubecf/values.yaml
  rules/ioutil/BUILD.bazel
  rules/ioutil/def.bzl
  rules/kubecf/BUILD.bazel
  rules/kubecf/def.bzl
  rules/kubecf/image_list.tmpl.rb
Labels: Priority: Critical, Status: Verification Needed, Type: Maintenance

#567 Fix. Modified the database initialization sequence.
  deploy/helm/kubecf/assets/scripts/jobs/pxc/functions.sh
Labels: SUSE, Type: Bug

#489 Use a PVC for diego cell ephemeral disks
  bosh/releases/pre_render_scripts/diego-cell/garden/jobs/patch_pre-start.sh
  bosh/releases/pre_render_scripts/diego-cell/rep/bpm/patch_bpm.sh
  deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml
  deploy/helm/kubecf/values.yaml
Labels: Priority: High, Status: Verification Needed, Type: Bug

#565 CAP CI: implement pools
  .concourse/cap-release/README.md
  .concourse/cap-release/create_cap-release_pipeline.sh
  .concourse/cap-release/pipeline.template
Labels: Priority: High, Status: Verification Needed, Type: CI
