Repository cloudfoundry-incubator/kubecf, pull requests merged in 2020-12, with the labels that each got.

#1635 fix: releases: bump postgres to 43
  chart/config/releases.yaml
Labels: Type: Maintenance

#1639 fix: backport YAML parsing fixes from CAPI-1.101.0
  bosh/releases/pre_render_scripts/api/cloud_controller_ng/jobs/patch-cc.sh
  bosh/releases/pre_render_scripts/cc-worker/cloud_controller_worker/jobs/patch-cc.sh
  bosh/releases/pre_render_scripts/scheduler/cloud_controller_clock/jobs/patch-cc.sh
  chart/assets/operations/instance_groups/cc-worker.yaml
Labels: Priority: Critical, changelog

#1637 feat: remove cc_deployment_updater.
  chart/assets/operations/instance_groups/database.yaml
  chart/assets/operations/instance_groups/scheduler.yaml
  chart/config/jobs.yaml
  chart/config/resources.yaml
  chart/templates/_capi.tpl
Labels: Type: Bug

#1641 fix: bump garden-runc to 1.19.17
  bosh/releases/pre_render_scripts/diego-cell/garden/jobs/patch_pre-start.sh
  chart/config/releases.yaml
Labels: Priority: High, changelog, suse-cap

#1654 fix: update cf-operator-delete logic
  scripts/cf-operator-delete.sh
Labels: Type: Bug
