Repository cloudfoundry-incubator/kubecf, pull requests merged in 2020-07, with the labels that each got.

#1056 Add documentation for values.yaml
  .concourse/pipeline.yaml.gomplate
  deploy/helm/kubecf/BUILD.bazel
  deploy/helm/kubecf/templates/implicit_vars.yaml
  deploy/helm/kubecf/values.yaml
  rules/kubecf/BUILD.bazel
  rules/kubecf/create_sample_values.rb
  rules/kubecf/def.bzl
  rules/kubecf/values_documentation_check.tmpl.sh
Labels: Priority: High, Type: Documentation, suse-cap

#1096 Add the ability to disable the database
  deploy/helm/kubecf/assets/operations/instance_groups/database.yaml
Labels: Priority: High, Status: Verification Needed, changelog

#1108 CI: Ensure cluster resources between pipelines don't collide
  .concourse/kubecf.yaml
  .concourse/pipeline.yaml.gomplate
  .concourse/tasks/upgrade.sh
Labels: Priority: High

#1083 Remove `v` from kubecf's version string, and consume correctly
  .concourse/pipeline.yaml.gomplate
  doc/release/release-guidelines.md
  rules/helm/package.tmpl.rb
  scripts/version.sh
Labels: Priority: Medium, Type: Maintenance

#1152 Fix 'all' Makefile target
  Makefile
  scripts/README.md
  scripts/kubecf-apply.sh
  scripts/kubecf-build.sh
Labels: Priority: Medium, Type: Bug

#1107 enable diego-cell departed deployment feature to support multi-clusters
  deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml
  deploy/helm/kubecf/templates/bosh_deployment.yaml
  deploy/helm/kubecf/templates/diego-cell-isolation-segment-services.yaml
  deploy/helm/kubecf/templates/diego-cell-isolation-segment.yaml
  deploy/helm/kubecf/values.yaml
Labels: Type: Enhancement

#1159 fix: scripts: Fix minikube ISO download URL
  scripts/minikube-start.sh
Labels: Type: Bug

#1110 docs: replace breaking change commit definition
  doc/architecture/decisions/0002-git-commit-messages.md
Labels: Priority: Medium, Type: Documentation

#1169 fix: scripts: Deal with re-running tests better
  scripts/test.sh
Labels: Priority: Low, Size: 1, Type: Bug
