Repository cloudfoundry-incubator/kubecf, pull requests merged in 2020-01, with the labels that each got.

#288 Fix post-start for diego-api passive instance(s)
  deploy/helm/kubecf/assets/operations/instance_groups/diego-api.yaml
Labels: Type: Bug

#286 Bump minikube to v1.6.2
  def.bzl
Labels: Priority: High, Type: Enhancement

#296 [GKE] allow setting svc spec.loadBalancerIP for GKE reserved/static IPs
  deploy/helm/kubecf/templates/ingress.yaml
  deploy/helm/kubecf/values.yaml
Labels: Priority: High, Type: Bug

#294 Drone registry caches
  .drone/deploy/runner/def.bzl
  .drone/deploy/runner/start.sh
  .drone/pipelines/default/steps/deploy/kind.sh
  def.bzl
  dev/kind/start.sh
Labels: Type: CI

#300 Fixed gorouter http target port
  deploy/helm/kubecf/assets/operations/instance_groups/router.yaml
  deploy/helm/kubecf/templates/ingress.yaml
Labels: Type: Bug

#221 docs: Describes the git commit message approach
  doc/architecture/decisions/0002-git-commit-messages.md
Labels: Priority: Low, Type: Documentation

#301 Exposed the healthcheck port for tcp-router
  deploy/helm/kubecf/templates/ingress.yaml
Labels: Type: Bug

#305 Bumped CATS release to 0.0.9
  deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
  deploy/helm/kubecf/values.yaml
Labels: Type: Bug

#302 Added annotations option for services
  deploy/helm/kubecf/templates/ingress.yaml
  deploy/helm/kubecf/values.yaml
Labels: Type: Enhancement

#354 fix: Eirini's loggregator extension in WARN level
  deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
Labels: Type: Bug

#314 Enabling SUSE buildpacks on Cloud Controller
  bosh/releases/pre_render_scripts/api/suse-binary-buildpack/ig_resolver/patch_job_mf.sh
  bosh/releases/pre_render_scripts/api/suse-binary-buildpack/jobs/create_bosh_pre_start.sh
  bosh/releases/pre_render_scripts/api/suse-dotnet-core-buildpack/ig_resolver/patch_job_mf.sh
  bosh/releases/pre_render_scripts/api/suse-dotnet-core-buildpack/jobs/create_bosh_pre_start.sh
  bosh/releases/pre_render_scripts/api/suse-go-buildpack/ig_resolver/patch_job_mf.sh
  bosh/releases/pre_render_scripts/api/suse-go-buildpack/jobs/create_bosh_pre_start.sh
  bosh/releases/pre_render_scripts/api/suse-java-buildpack/ig_resolver/patch_job_mf.sh
  bosh/releases/pre_render_scripts/api/suse-java-buildpack/jobs/create_bosh_pre_start.sh
  bosh/releases/pre_render_scripts/api/suse-nginx-buildpack/ig_resolver/patch_job_mf.sh
  bosh/releases/pre_render_scripts/api/suse-nginx-buildpack/jobs/create_bosh_pre_start.sh
  bosh/releases/pre_render_scripts/api/suse-nodejs-buildpack/ig_resolver/patch_job_mf.sh
  bosh/releases/pre_render_scripts/api/suse-nodejs-buildpack/jobs/create_bosh_pre_start.sh
  bosh/releases/pre_render_scripts/api/suse-php-buildpack/ig_resolver/patch_job_mf.sh
  bosh/releases/pre_render_scripts/api/suse-php-buildpack/jobs/create_bosh_pre_start.sh
  bosh/releases/pre_render_scripts/api/suse-python-buildpack/ig_resolver/patch_job_mf.sh
  bosh/releases/pre_render_scripts/api/suse-python-buildpack/jobs/create_bosh_pre_start.sh
  bosh/releases/pre_render_scripts/api/suse-ruby-buildpack/ig_resolver/patch_job_mf.sh
  bosh/releases/pre_render_scripts/api/suse-ruby-buildpack/jobs/create_bosh_pre_start.sh
  bosh/releases/pre_render_scripts/api/suse-staticfile-buildpack/ig_resolver/patch_job_mf.sh
  bosh/releases/pre_render_scripts/api/suse-staticfile-buildpack/jobs/create_bosh_pre_start.sh
  deploy/helm/kubecf/assets/operations/buildpacks/set_suse_buildpacks.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/diego-cell.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/sle15-stack.yaml
  deploy/helm/kubecf/templates/bosh_deployment.yaml
  deploy/helm/kubecf/templates/ops.yaml
  deploy/helm/kubecf/values.yaml
Labels: Priority: High, Type: Maintenance

#363 Bump KubeCF to 0.2.0
  def.bzl
Labels: Priority: High, Status: Verification Needed, Type: CI

#360 Add Concourse post-publish pipeline
  .concourse/README.md
  .concourse/post_publish.yaml
Labels: Priority: High, Status: Verification Needed, Type: CI

#365 fix: loggregator DNS spam
  deploy/helm/kubecf/assets/operations/instance_groups/acceptance-tests.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/app-autoscaler.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/bits.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/brain-tests.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/database.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/eirini.yaml
  deploy/helm/kubecf/assets/operations/releases.yaml
  deploy/helm/kubecf/assets/operations/set_release_urls.yaml
  deploy/helm/kubecf/values.yaml
Labels: Priority: High, Type: Bug, Type: Maintenance

#356 Automatic Helm chart versioning
  .bazelrc
  .drone/pipelines/default/runtime/config.sh
  .drone/pipelines/default/steps/build/output_chart.sh
  .drone/pipelines/default/steps/deploy/kubecf.sh
  .gitlab-ci.yml
  .gitlab/pipelines/runtime/config.sh
  .gitlab/pipelines/stages/build/build.sh
  .gitlab/pipelines/stages/build/output_chart.sh
  .gitlab/pipelines/stages/deploy/deploy_kubecf.sh
  .gitlab/pipelines/stages/publish.sh
  BUILD.bazel
  WORKSPACE
  def.bzl
  deploy/bundle/BUILD.bazel
  deploy/helm/kubecf/BUILD.bazel
  deploy/helm/kubecf/Chart.yaml
  dev/kubecf/BUILD.bazel
  dev/linters/BUILD.bazel
  rules/helm/BUILD.bazel
  rules/helm/def.bzl
  rules/helm/package.sh
  rules/helm/package.tmpl.rb
  rules/workspace_status/BUILD.bazel
  rules/workspace_status/WORKSPACE
  rules/workspace_status/def.bzl
  rules/workspace_status/status_converter.tmpl.sh
  rules/workspace_status/status_merger.tmpl.sh
  workspace_status.rb
Labels: Priority: Medium, Status: Verification Needed, Type: Enhancement

#367 fix: label name and unmarkComment flag to false
  .github/stale.yml
Labels: Priority: Medium, Status: Verification Needed, Type: Maintenance
