Repository cloudfoundry-incubator/kubecf, pull requests merged in 2020-08, with the labels that each got.

#994 Replace serialization hints with explicit cf-operator wait-for.
  deploy/helm/kubecf/assets/operations/sequencing.yaml
  dev/kube/ig-tools/README.md
  dev/kube/ig-tools/extent.sh
  dev/kube/ig-tools/sequence.rb
  dev/kube/ig-tools/upwatch.rb
Labels: suse-cap

#1074 ADR for upgrade testing
  doc/architecture/decisions/0004-upgrade-testing.md
Labels: Priority: High, Type: Maintenance

#1236 Remove trailing spaces
  .github/workflows/pull-request-ci.yaml
Labels: pr-test-queue

#1242 feat: add validation label so it can be easily identified before moved to a project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Priority: Medium, Status: Verification Needed, Type: Maintenance

#1249 fix: kubecf#1181. Have rep set kernel parameters
  bosh/releases/pre_render_scripts/diego-cell/rep/jobs/patch_set_kernel.sh
  chart/assets/operations/instance_groups/diego-cell.yaml
Labels: Priority: Critical, Type: Bug, Type: Documentation

#1223 RFD-0000: Proposal to Include RFDs in Future System Changes
  doc/rfd/0000/README.md
  doc/rfd/prototype/README.md
Labels: Priority: High, Status: Validation, Type: RFD

#1267 feat: add conventional GH action
  .commitsar.yaml
  .github/workflows/conventional-commits-lit.yml
Labels: Priority: Medium, Type: Maintenance

#1268 fix: correct a typo and add newline to the config file.
  .commitsar.yaml
  .github/workflows/conventional-commits-lit.yml
Labels: Type: Bug

#1266 Return empty string when looking up non-existing properties
  chart/templates/_config.tpl
  tests/config/templates/lookup.yaml
Labels: Type: Bug

#1270 feat: remove old GitHub action and add new one that checks PR titles
  .commitsar.yaml
  .github/workflows/conventional-commits-lit.yml
Labels: Type: Maintenance
