Repository cloudfoundry-incubator/kubecf, pull requests merged in 2020-05, with the labels that each got.

#798 fix: check for stemcell semver
  .concourse/suse-buildpacks-ci/buildpack-version-bump/tasks/create_pr.sh
  .concourse/suse-buildpacks-ci/stemcell-version-bump/tasks/create_pr.sh
Labels: Type: CI

#809 fix: use the helm dependencies rules
  WORKSPACE
  deploy/helm/kubecf/BUILD.bazel
  deploy/helm/kubecf/requirements.lock
  deploy/helm/kubecf/requirements.yaml
  rules/helm/package.tmpl.rb
Labels: Priority: High, Type: Bug

#775 fix: database charset and collate
  deploy/helm/kubecf/assets/scripts/jobs/pxc/migrate_charset.sh
  deploy/helm/kubecf/assets/scripts/jobs/pxc/seeder.sh
  deploy/helm/kubecf/templates/database.yaml
Labels: changelog

#814 feat: Implement credentials and variables settings in values.yaml
  deploy/helm/kubecf/templates/bosh_deployment.yaml
  deploy/helm/kubecf/templates/credentials.yaml
  deploy/helm/kubecf/templates/implicit_vars.yaml
  deploy/helm/kubecf/values.yaml
Labels: Priority: Critical, suse-cap

#832 fix: repackage using helm instead of tar
  rules/kubecf/release_chart.sh
Labels: Priority: Critical, Type: Bug

#858 feat: bump brain tests to v0.0.12
  deploy/helm/kubecf/assets/operations/instance_groups/brain-tests.yaml
  deploy/helm/kubecf/values.yaml
Labels: Type: Maintenance

#864 fix: shellcheck linting errors
  .concourse/tasks/upgrade.sh
Labels: Type: Bug

#853 fix: Use correct encryption key labels
  deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
Labels: changelog, suse-cap

#917 fix: deploy: move sample values into kubecf chart
  deploy/bundle/BUILD.bazel
  deploy/helm/kubecf/BUILD.bazel
  rules/helm/def.bzl
Labels: suse-cap

#922 fix: Cherry Pick "fix: deploy: move sample values into kubecf chart #917"
  deploy/bundle/BUILD.bazel
  deploy/helm/kubecf/BUILD.bazel
  rules/helm/def.bzl
Labels: suse-cap

#921 fix: Cherry Pick "Bump smoke-tests to increase app memory limit #920"
  deploy/helm/kubecf/values.yaml
Labels: suse-cap

#929 feat: Cherry Pick helm README and icon file
  deploy/helm/kubecf/Chart.yaml
  deploy/helm/kubecf/README.md
  icon/kubecf.png
Labels: suse-cap

#854 feat: update enc key rotation docs
  doc/Contribute.md
  doc/encryption_key_rotation.md
  doc/secret_rotation.md
  doc/secret_rotation_general.md
Labels: suse-cap
