Repository cloudfoundry-incubator/kubecf, pull requests merged in 2020-09, with the labels that each got.

#1273 fix: missing loadBalancerIP on values.yaml
  chart/values.schema.yaml
  chart/values.yaml
Labels: Type: Maintenance

#1281 fix: Rename GitHub action that validates the PR title semantics.
  .github/workflows/conventional-commits-lit.yml
Labels: Type: Maintenance

#1288 fix: scripts/kubecf-wait: no longer wait for dm
  scripts/kubecf-wait.sh
Labels: Type: Bug

#1292 fix: image_list.rb: use $defaults for release name
  scripts/image_list.rb
Labels: Type: Bug

#1295 feat: Add tolerations for instance groups
  chart/assets/operations/sizing.yaml
  chart/templates/bosh_deployment.yaml
  chart/templates/ops.yaml
  chart/values.schema.yaml
Labels: suse-cap

#1301 fix: replace pull_request trigger with pull_request_target to include forks
  .github/workflows/conventional-commits-lit.yml
Labels: Priority: Medium, Type: Maintenance

#1300 fix: Add back v before semver into published artifacts
  .concourse/pipeline.yaml.gomplate
Labels: Priority: Medium, Status: Do NOT Merge

#1161 docs: ADR for restricting scripting to ruby and bash
  doc/architecture/decisions/005-bash-and-ruby.md
Labels: pr-test-queue

#1321 fix: apps-dns: change certs when using eirini
  chart/assets/operations/instance_groups/diego-cell.yaml
  chart/assets/operations/instance_groups/scheduler.yaml
Labels: Type: Bug

#1322 feat: move current ADR documents into RFD structure
  doc/rfd/0001/README.md
  doc/rfd/0002/README.md
  doc/rfd/0003/README.md
  doc/rfd/0004/README.md
  doc/rfd/0005/README.md
  doc/rfd/README.md
Labels: Type: Documentation

#1326 fix: add the pull request links for each RFD
  doc/rfd/0000/README.md
  doc/rfd/0001/README.md
  doc/rfd/0002/README.md
  doc/rfd/0003/README.md
  doc/rfd/0004/README.md
Labels: Type: Documentation

#1325 fix: chart: public svcs: don't select on version
  chart/templates/ingress.yaml
Labels: Type: Bug

#1275 feat: Implement eirini-dns-aliases
  chart/templates/_helpers.tpl
  chart/values.schema.yaml
  mixins/eirinix/config/eirinix.yaml
  mixins/eirinix/templates/dns-aliases/deployment.yaml
  mixins/eirinix/templates/dns-aliases/service.yaml
Labels: changelog

#1339 fix: move all the rfds into an specific rfd folder.
  doc/rfd/rfd/0000/README.md
  doc/rfd/rfd/0001/README.md
  doc/rfd/rfd/0002/README.md
  doc/rfd/rfd/0003/README.md
  doc/rfd/rfd/0004/README.md
  doc/rfd/rfd/0005/README.md
Labels: Type: Maintenance

#1387 fix: chart: update operator docs links
  chart/README.md
Labels: Type: Bug

#1353 fix: remove the validation label
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Type: Documentation

#1403 fix: Avoid naming conflict for templates/rbac.yaml between chart and mixins/eirinix
  chart/config/eirini.yaml
  mixins/eirinix/templates/eirinix-rbac.yaml
  mixins/eirinix/templates/eirinix-ssh-proxy.yaml
  mixins/eirinix/templates/eirinix-ssh.yaml
Labels: Priority: Critical, Type: Bug

#1388 feat: support seeding external database
  chart/assets/operations/instance_groups/database.yaml
  chart/assets/scripts/jobs/pxc/seeder.sh
  chart/templates/_config.tpl
  chart/templates/database.yaml
  chart/templates/database/_database.tpl
  chart/templates/database/db-configmaps.yaml
  chart/templates/database/db-migrate-charset.yaml
  chart/templates/database/db-secrets.yaml
  chart/templates/database/db-seeder.yaml
  chart/templates/database/db-services.yaml
  chart/templates/database/db-statefulset.yaml
  chart/templates/implicit_vars.yaml
  chart/values.schema.yaml
  chart/values.yaml
Labels: Type: Enhancement
