Repository cloudfoundry-incubator/kubecf, pull requests merged in 2020-11, with the labels that each got.

#1433 feat: RFD 8 Public Roadmap
  doc/rfd/README.md
  doc/rfd/rfd/0008/README.md
Labels: Type: RFD

#1526 fix: move tcp-router healthcheck port to avoid clash
  chart/assets/operations/instance_groups/tcp-router.yaml
  chart/templates/ingress.yaml
Labels: suse-cap

#1502 feat: Improvements to GitHub Actions workflow
  .github/workflows/README.md
  .github/workflows/pull-request-ci.yaml
  .github/workflows/pull-request-lint.yaml
  .github/workflows/pull-request-schedule.yaml
  .github/workflows/pull-request-schedule/find-jobs.js
  .github/workflows/pull-request-schedule/trigger-builds.js
Labels: Type: CI

#1605 fix: don't define Eirini cluster role when deploying Diego
  mixins/eirini/templates/eirini-cluster-role.yaml
  mixins/eirini/templates/metrics-service-account.yml
Labels: Priority: Low, Type: Bug

#1615 fix: avoid generating ops that reference instance groups that don't exist
  chart/templates/_config.tpl
  chart/templates/_multicluster.tpl
  chart/templates/multiple_cluster_mode.yaml
Labels: Type: Bug

#1531 feat: use generic fog provider for external blobstore
  chart/assets/operations/instance_groups/singleton-blobstore.yaml
  chart/templates/_capi.tpl
  chart/templates/_features.tpl
  chart/templates/bosh_deployment.yaml
  chart/templates/fog-blobstore.yaml
  chart/templates/ops.yaml
  chart/templates/s3-blobstore.yaml
  chart/values.schema.yaml
  chart/values.yaml
  mixins/bits/config/bits.yaml
  mixins/bits/templates/bits-config.yaml
  mixins/bits/templates/bits.yaml
  scripts/image_list.rb
  scripts/kubecf-build.sh
Labels: changelog, suse-cap

#1606 fix: add more information in how to handle new github issues.
  CONTRIBUTING.md
Labels: Priority: Medium, Type: Documentation
