Repository cloudfoundry-incubator/kubecf, pull requests merged in 2020-06, with the labels that each got.

#958 CI: fix filename for suse-java-buildpack.
  .concourse/suse-buildpacks-ci/buildpack-version-bump/pipeline.yaml.gomplate
  .concourse/suse-buildpacks-ci/buildpack-version-bump/tasks/create_pr.sh
  .concourse/suse-buildpacks-ci/stemcell-version-bump/pipeline.yaml.gomplate
Labels: SUSE, Type: CI

#943 feat: updating kube ready state check
  dev/kube/kube-ready-state-check.sh
Labels: SUSE

#1031 Remove unneeded vars in the upgrade task of the kubecf pipeline
  .concourse/tasks/upgrade.sh
Labels: Priority: High

#1040 Remove all the patches removing `ulimit` calls
  bosh/releases/pre_render_scripts/api/cloud_controller_ng/jobs/patch_cc_uploader_ctl.sh
  bosh/releases/pre_render_scripts/api/cloud_controller_ng/jobs/patch_cloud_controller_api_ctl.sh
  bosh/releases/pre_render_scripts/api/cloud_controller_ng/jobs/patch_file_server_ctl.sh
  bosh/releases/pre_render_scripts/auctioneer/auctioneer/jobs/patch_auctioneer_ctl.sh
  bosh/releases/pre_render_scripts/diego-api/bbs/jobs/patch_bbs_ctl.sh
  bosh/releases/pre_render_scripts/diego-api/locket/jobs/patch_locket_ctl.sh
  bosh/releases/pre_render_scripts/diego-cell/rep/jobs/patch_rep_ctl.sh
  bosh/releases/pre_render_scripts/router/gorouter/jobs/patch_pre-start.sh
  bosh/releases/pre_render_scripts/scheduler/ssh_proxy/jobs/patch_ssh_proxy_ctl.sh
Labels: Priority: High

#1044 Pipeline: Remove kubecf-login from upgrade task.
  .concourse/tasks/upgrade.sh
Labels: Priority: Medium

#1061 Don't call kubecf-login on upgrade.sh
  .concourse/tasks/upgrade.sh
Labels: Type: Maintenance

#1041 Expand pipeline docs for copies of the pipeline
  .concourse/README.md
  .concourse/kubecf.yaml
Labels: Priority: Medium, Type: Documentation

#1067 CI: Move green jobs to the production tab
  .concourse/pipeline.yaml.gomplate
Labels: Priority: High, Status: Verification Needed, Type: Maintenance

#967 update autoscaler to 3.0.1 and add mysql support
  deploy/helm/kubecf/assets/operations/azs.yaml
  deploy/helm/kubecf/assets/operations/instance_groups/database.yaml
  deploy/helm/kubecf/templates/database.yaml
  deploy/helm/kubecf/values.yaml
Labels: Status: Approved, Type: Maintenance, suse-cap

#1070 Add comment on why we cannot upstream the routing-api bpm patch
  bosh/releases/pre_render_scripts/routing-api/routing-api/bpm/patch_bpm.sh
Labels: Priority: High, Status: Approved
