Repository cloudfoundry-incubator/kubecf, pull requests merged in 2020-02, with the labels that each got.

#374 Documentation explaining the process for general secret rotation
  doc/Contribute.md
  doc/secret_rotation_general.md
Labels: Priority: Medium, Type: Documentation

#383 feat: SLE15 stemcell consolidation
  deploy/helm/kubecf/values.yaml
Labels: Priority: Medium, Status: Verification Needed, Type: Enhancement

#392 Fix metadata generation for version interpolation
  deploy/helm/kubecf/BUILD.bazel
Labels: Priority: High, Trigger: CI

#387 Bump Helm to version 3.0.3
  .drone/pipelines/default/runtime/config.sh
  .drone/pipelines/default/steps/deploy/kubecf.sh
  .gitlab/pipelines/runtime/config.sh
  .gitlab/pipelines/stages/deploy/deploy_kubecf.sh
  def.bzl
  deploy/helm/kubecf/Chart.yaml
  dev/cf_operator/BUILD.bazel
  dev/kubecf/BUILD.bazel
  dev/kubecf/README.md
  rules/helm/BUILD.bazel
  rules/helm/def.bzl
  rules/helm/delete.tmpl.rb
  rules/helm/package.tmpl.rb
  rules/helm/template.sh
  rules/helm/upgrade.tmpl.rb
Labels: Priority: High, Status: Verification Needed, Type: Enhancement

#403 Feature: Debug support. Print helm commands generated by bazel rules.
  rules/helm/delete.tmpl.rb
  rules/helm/upgrade.tmpl.rb
Labels: Type: Enhancement

#406 Bump cf-operator to 3.1.0
  def.bzl
Labels: Priority: High, SUSE, Status: Verification Needed, Type: Maintenance

#404 Add SITs instance group
  deploy/helm/kubecf/assets/operations/instance_groups/sync-integration-tests.yaml
  deploy/helm/kubecf/assets/operations/releases.yaml
  deploy/helm/kubecf/templates/sync-integration-tests.yaml
  deploy/helm/kubecf/values.yaml
  doc/tests.md
  doc/tests_sits.md
  testing/sync_integration_tests/BUILD.bazel
  testing/sync_integration_tests/trigger.yaml
Labels: Priority: High, SUSE, Status: Verification Needed, Type: CI

#409 CF deployment bump to 12.33.0
  def.bzl
  deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
  deploy/helm/kubecf/values.yaml
Labels: Priority: Critical, Status: WIP, Trigger: CI

#390 docs: Update release flow
  doc/release/release.md
Labels: Priority: High, Status: Verification Needed, Trigger: CI, Type: Documentation

#388 docs: transfer to upstream repo
  CONTRIBUTING.md
  README.md
  code-of-conduct.md
Labels: Priority: Medium, Status: Blocked, Status: Do NOT Merge, Type: Documentation

#391 Add options to support external DB TLS
  deploy/helm/kubecf/assets/operations/instance_groups/database.yaml
  deploy/helm/kubecf/assets/operations/releases.yaml
  deploy/helm/kubecf/values.yaml
Labels: Trigger: CI

#416 fix: remove broken Gitlab
  .gitlab-ci.yml
  .gitlab/deploy/runner/kubernetes/BUILD.bazel
  .gitlab/deploy/runner/kubernetes/README.md
  .gitlab/deploy/runner/kubernetes/deploy.sh
  .gitlab/deploy/runner/kubernetes/ephemeral_volume_k3s.yaml
  .gitlab/deploy/runner/kubernetes/values.yaml
  .gitlab/pipelines/runtime/binaries.sh
  .gitlab/pipelines/runtime/config.sh
  .gitlab/pipelines/stages/deploy/deploy_cf_operator.sh
  .gitlab/pipelines/stages/deploy/deploy_kubecf.sh
  .gitlab/pipelines/stages/deploy/setup_k8s.sh
  .gitlab/pipelines/stages/deploy/stop_k8s.sh
  .gitlab/pipelines/stages/deploy/wait_cf_operator.sh
  .gitlab/pipelines/stages/deploy/wait_kubecf.sh
  .gitlab/pipelines/stages/publish.sh
  .gitlab/pipelines/stages/tests/cf_acceptance_tests.sh
  .gitlab/pipelines/stages/tests/smoke_tests.sh
Labels: Type: CI

#413 CF deployment bump 12.33
  deploy/helm/kubecf/assets/operations/instance_groups/api.yaml
  deploy/helm/kubecf/values.yaml
  doc/cf_deployment/bump.md
Labels: Priority: Critical, SUSE
